#vscore remote ssh in boot2docker
FROM ubuntu:18.04
MAINTAINER ranran9

#install sshd
RUN apt-get update && apt-get install -y ssh curl tar

ENV USER=vscode
ENV USER_PASS=tcuser
ENV SHELL=/bin/bash

RUN useradd -s /bin/bash -u 1000 -g 50 -G sudo,100 -m ${USER} && \
  echo "${USER}:${USER_PASS}" | chpasswd

USER root

#install docker client
ENV DOCKER_VERSION=19.03.5
RUN curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz \
  | tar -xzC /usr/local/bin --strip=1 docker/docker

EXPOSE 22

RUN mkdir /run/sshd
CMD ["/usr/sbin/sshd", "-D"]